# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Scrolling' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
	source 'https://github.com/CocoaPods/Specs.git'
	platform :ios, '10.0'
  use_frameworks!

  # Pods for Scrolling
	pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'
	pod 'Firebase/Core'
	pod 'Firebase/Auth'

  target 'ScrollingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
